### ISSUE TITLE
notepad.exeで文字の幅の比が崩れる

### ISSUE THREAD

**Issue by sarubo** [yuru7/juisee#1]
notepad.exe で Releases v0.0.3 の juisee を指定した時に文字の幅の比が崩れます。

また --half-width を指定して自分でビルドしたものも同様に崩れます。

vscode や Windows Terminal では問題なく動作します。

### Screenshots

notepad.exe で juisee を指定した時の様子

![image](https://github.com/yuru7/juisee/assets/47109823/4d370359-c6b4-4776-ab49-1f09c0533a84)

### OS

Windows 10 22H2

**Comment by yuru7** [comment]
どのフォント、どのテキストエディタにおいても、フォントサイズによっては半角文字と全角文字で桁位置が想定とずれる現象は起こりえます。

環境によって奇数サイズまたは偶数サイズのいずれかで揃うことが多いです。OSが同じでも画面解像度によって奇数・偶数どちらでずれるかが変わることもあり、一概にどのサイズにすれば直るとは言えませんので、ご自身の環境でフォントサイズを2程度上下させてみて、想定通りの 3:5 幅に揃うサイズにしてみてください。

**Comment by yuru7** [comment]
ちなみに私の環境 Windows 11 22H2 のメモ帳では、フォントサイズ11と15で揃うようでした。13で揃っているわけではないあたり、奇数だからといって揃うわけではないようですね。このあたりのOSにおけるフォント描画の仕様は分かりかねますが、このようにフォントサイズによってずれるのはよくあることなので、割り切っていただくしかないかと思います。

ちなみに、Meryなどのようなテキストエディタによっては、等幅フォントにおいてこういった桁ズレに対処している例もありますが、Juiseeの標準は 3:5 幅であり、これは内部的にはプロポーショナルフォント扱いですから、こういった対処の恩恵も受けられなかったりします。

https://www.haijin-boys.com/software/mery/mery-2-5-5

> DirectWrite 有効時の固定ピッチフォントの文字幅を強制的に GDI のフォントに合わせる隠しオプションを追加

どうしても桁ズレが困る場面でしたら、1:2幅のフォントの方が相性はいいかもしれませんね。

---

Size 10:
![image](https://github.com/yuru7/juisee/assets/13458509/e30adb3e-0404-4cc6-b722-465aad545bb1)

Size 11:
![image](https://github.com/yuru7/juisee/assets/13458509/8a96350b-8b1e-4823-ba87-c4a459626651)

Size 12:
![image](https://github.com/yuru7/juisee/assets/13458509/6d14bdfd-da67-4e03-bb56-6a21865fab70)

Size 13:
![image](https://github.com/yuru7/juisee/assets/13458509/12479ab0-52ca-486b-9ec8-103a830ea38a)

Size 14:
![image](https://github.com/yuru7/juisee/assets/13458509/8186d556-bd9f-4b61-8760-c6467b67839e)

Size 15:
![image](https://github.com/yuru7/juisee/assets/13458509/73f9306a-63eb-43fd-ad2a-18f795102c2f)

**Comment by sarubo** [comment]
OSにおけるフォント描画の仕様やソフトウェア、文字サイズによるところがあるのですね。HackGen Consoleではこのようなことは起きて来なかったため驚いてしました。

とりあえず文字サイズを変更することで対処しようと思います。ありがとうございました。
