### ISSUE TITLE
フォントファミリー名の余分なスペース

### ISSUE THREAD

**Issue by conjLob** [yuru7/juisee#2]
バリエーションオプション無しの場合、フォントファミリー名の末尾に余分なスペースが入っていそうです。

```pwsh
PS C:\> [System.Drawing.FontFamily]::Families | Select-String "Juisee"

[FontFamily: Name=Juisee ]
[FontFamily: Name=Juisee HW]
```

そのため VS Code などではスペース付きで指定する必要がありました。

<img width="385" alt="image" src="https://github.com/yuru7/juisee/assets/53427774/6db93a4f-fa84-44eb-b5f8-d55c3b53a9e1">

使用しているバージョンは v0.0.4 です。

**Comment by yuru7** [comment]
@conjLob 
ご報告ありがとうございます。うっかりしてしまいました。

修正したリリース v0.0.5 を公開しましたので、お暇なときにご確認ください。

**Comment by conjLob** [comment]
対応ありがとうございます！修正を確認できました
