### ISSUE TITLE
WindowsのEmacsで日本語フォント部分が認識されない

### ISSUE THREAD

**Issue by ujimushi** [yuru7/juisee#3]
主にLinux上のEmacsエディタでJulia言語を使っているものです。
今まではUDEV Gothicを使っていましたが，最近Jusieeフォントに変更して使っています。

そこで，Windows上のEmacsでも使ってみようということで，設定してみると日本語のフォントがうまく認識しないようでした。
![example-windows-emacs-display](https://github.com/yuru7/juisee/assets/10514830/dab803f2-e7c5-4f9f-9f0e-9ce9ef6ec4ae)

よくよく調べてみると，Windows上のEmacsはJusieeフォントを韓国語のフォントとして認識しているためではないかという疑念を持ちました。
次の画面はGUIのフォント選択画面を表示したものです。
![Juisee-windows-font-selector](https://github.com/yuru7/juisee/assets/10514830/6c7c427e-8a9f-40d6-b307-36c78e71150d)

次に，LINESeedJPとJuiseeフォントのOS/2の文字セット情報をFontForgeで表示したものです。
これを見ると，LINESeedJPではCJKの中ではcodepage 932で日本語となっているのが，Jusieeでは韓国語のcodepageになっているようです。Pythonのソースを見ると特に変更していないので，意図せず変わっているのだと思われます。
![lineseedjp-os2](https://github.com/yuru7/juisee/assets/10514830/cc101a92-5941-4270-a445-7c49769a4101)

![juisee-os2](https://github.com/yuru7/juisee/assets/10514830/e01521fb-e379-4934-a53e-b9edd3490528)
今のところwindowsのEmacsでしか不都合がない（VSCodeでは問題無さそう）ので，強い要望ということでもない（これまで通りUDEV Gothicを利用予定）のですが，もし可能であれば対応をお願いできたらと思います。

**Comment by yuru7** [comment]
@ujimushi 
ご報告ありがとうございます。
日本語コードページの問題に対処した [v0.0.6](https://github.com/yuru7/juisee/releases/tag/v0.0.6) を公開しました。
お暇なときに試してみてください。

**Comment by ujimushi** [comment]
対応ありがとうございます。
結果からいうと，日本語のコードページを追加していただいたv0.0.6を試してみましたがうまく表示できませんでした。
私が想定していた原因とは違ったようです。

ただ，Emacsが自動でencodingを認識しているところがうまくいってないのは間違いないようで，
色々調べてみると，
デフォルトのフォントセットの`unicode`に`Juisee`を指定する設定

```lisp
(set-fontset-font t 'unicode "Juisee")
```

を追加することで，うまく表示できるようになりました。(現行のv0.0.5でもうまくいきました)
これはLinux版のEmacsでも発生していたようで，今までは代わりに`UDEV Gothic`を表示していて違和感が無かっただけ
(以前から使っていたフォントのため)のようでした。

![juisee-display-japanese-fonts](https://github.com/yuru7/juisee/assets/10514830/23edd7f2-53b8-404b-8c36-b313e0eda066)

ネットで検索して色々調べてみると，Emacsの自動encoding設定でうまく表示できない例は
まれによくあるようで，同じJuliaMonoを用いた合成フォントである[JuGeMフォント](https://github.com/tohgarashi/JuGeM)でも同様の問題があり，同じ方法で表示可能でした。
Emacsの場合，設定側で対策するのはわりと普通の対応のようです。

最近使っていたRicty，UDEV Gothic等では特に問題がなかったので動揺してチケットを上げてしいました。
大変お騒がせしました。すみません。

Unicodeでも文字コードの範囲ごとに(例えば絵文字は別フォント等)設定する例もあるようですが，
Emacsで`Juisee`の日本語グリフを表示する最少設定追加としては上記で良さそうです。

お手数おかけしました。

#### 追記

個人的な好みでHWSZ版を手元でビルドして使っています。
スクリプトのオプションとしてだけでいいので「スラッシュゼロ」の出力機能を残しておいて欲しいです。

**Comment by yuru7** [comment]
原因違いだったとのことですが、解消できたようで何よりです。詳細な設定方法についても情報共有ありがとうございます。きっと同様の不具合があたった方の参考になると思います。

> スクリプトのオプションとしてだけでいいので「スラッシュゼロ」の出力機能を残しておいて欲しいです。

はい、オプションとしては今用意しているものを削除する予定はありません。「スペースは見えなくていいのに」「ゼロがスラッシュだったらなぁ」はHackGenをリリースした当初からよく聞こえてくる声でしたので、そういったこだわりある方に向けてご用意してみたものです。ご愛用いただけて嬉しいです。
