### ISSUE TITLE
CJK部分の「卍 U+534D」が半角幅になっている

### ISSUE THREAD

**Issue by ujimushi** [yuru7/juisee#4]
個人的にやりたいことがあってエディタで漢字の一覧のようなものを表示させていると，「卍」の文字が半角幅になっていました。

![Screenshot from 2024-06-18 21-38-46](https://github.com/yuru7/juisee/assets/10514830/db6bc6a0-b842-47bb-a662-0749bb2c1b3d)

こちらで色々調べてみるため，ソースフォルダ内のJuliaMonoフォントをFontForgeで開いてみると，
どうもJuliaMonoフォントのCJK部分の「卍 U+534D」にグリフ情報があり，これが影響を与えているようです。

![Screenshot from 2024-06-18 21-13-33](https://github.com/yuru7/juisee/assets/10514830/c9a16fb2-67bd-4e61-9eb8-0b23afbca4fc)

合成スクリプトを確認したところ，あらかじめJuliaMonoフォント内の「卍」グリフを削除しておくことで対策できそうな気がします。

```diff
--- fontforge_script.py~
+++ fontforge_script.py
@@ -210,6 +210,8 @@
     clear_glyph_range(dst_font, 0x30FB, 0x30FB)
     # WAVE DASH, FULLWIDTH TILDE
     src_font = copy_altuni(src_font, (0x301C,))
+    # 卍 U+534D
+    clear_glyph_range(dst_font, 0x534D, 0x534D)

     return src_font, dst_font
```

こちらの手持ちの環境では上の変更でビルドすると，「卍」がLine Seed JP由来のフォントに変わることを確認しました。

**Comment by yuru7** [comment]
ご報告ありがとうございます！
[v0.2.0](https://github.com/yuru7/juisee/releases/tag/v0.2.0) にて、修正しました。お試しください。

**Comment by ujimushi** [comment]
修正ありがとうございます。v0.2.0での修正確認しました。

一応こちらで追加で調べた参考情報として，

JuliaMono v0.050(Juisseのソース)時点で`卍`，v0.051～0.054のどこかで`点`が半角幅になっていて[Problem with CJK glyphs](https://github.com/cormullion/juliamono/issues/206)というイシューがたったのでv0.055では`卍`，`点`のグリフがJuliaMonoから削除されたようです。
ただ，この間にたくさんのグリフが追加，一部削除されているのでしばらくは今のバージョンのJuliaMonoで進める方がいい気がします。


後一つこのイシューとは関係なく気になった点として，U+FF0Dの「FULLWIDTH HYPHEN-MINUS」が未定義なのは仕様でしょうか?
ソースを見る限り意図せず消えてしまっているような感じがしていて，
できれば LineSeedJP 由来のグリフが入って欲しいなと思いました。(個人の感想です)

**Comment by yuru7** [comment]
情報ありがとうございます。
どうやら作者の意図として、全角の方が都合がいいとされる文字は削除する方針のようですね。
また、記号か漢字か判断できないものを推測で半角文字として投入する傾向もありそうです。よって、Julia Monoのバージョンを差し替えるのはよく注意した方がよさそうだなあと思いました。

**Comment by yuru7** [comment]
> U+FF0Dの「FULLWIDTH HYPHEN-MINUS」が未定義なのは仕様でしょうか？

上記については #5 にて、時間があるときに確認しますね
