### ISSUE TITLE
`--invisible-zenkaku-space` を有効にすると全角スペース（ `U+3000` ）のグリフが欠落する

### ISSUE THREAD

**Issue by gixim** [yuru7/juisee#7]
はじめに、素敵なフォントスクリプトをありがとうございます。

全角スペースを不可視にしたバリアントの生成を行ってみましたが、全角スペースを使う行が1対2（ないし3対5）の幅からずれてしまいます。
FontForgeで見てみると、LINE Seed由来のものが使われているはずの全角スペース（ `U+3000` ）のグリフ情報が失われてしまっているようでした。

![Screenshot 2024-08-20 210950](https://github.com/user-attachments/assets/067f0252-2ae8-4bcd-8146-820e1f10c841)

`make.ps1` のフォント生成箇所に `--invisible-zenkaku-space` オプションを追加して実行することで再現できると思います。

```pwsh
# 通常版
& "C:\Program Files (x86)\FontForgeBuilds\bin\fontforge.exe" --lang=py -script .\fontforge_script.py --invisible-zenkaku-space `
    && Get-ChildItem .\build\fontforge_Juisee*.ttf | ForEach-Object { python -m ttfautohint --dehint --no-info $_.FullName $_.FullName } `
    && python fonttools_script.py `
    && Copy-Item -Path .\build\*.ttf -Destination $move_dir_normal -Force

# 半角1:全角2版
& "C:\Program Files (x86)\FontForgeBuilds\bin\fontforge.exe" --lang=py -script .\fontforge_script.py --half-width --invisible-zenkaku-space `
    && Get-ChildItem .\build\fontforge_Juisee*.ttf | ForEach-Object { python -m ttfautohint --dehint --no-info $_.FullName $_.FullName } `
    && python fonttools_script.py `
    && Copy-Item -Path .\build\*.ttf -Destination $move_dir_normal -Force
```

Windows 11 Homeを使ってビルドを実行しました。
その他のバージョン情報はこちらのとおりです。

```
$ python --version
Python 3.12.5

$ pip list
Package        Version
-------------- -------
fonttools      4.40.0
pip            24.2
setuptools     72.2.0
ttfautohint-py 0.5.1

$ fontforge --version
Copyright (c) 2000-2023. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20230101
 Based on sources from 2023-01-01 05:31 UTC-ML-TtfDb-D-GDK3.
 Based on source from git with hash: a1dad3e81da03d5d5f3c4c1c1b9b5ca5ebcfcecf
fontforge 20230101
build date: 2023-01-01 05:31 UTC
```

**Comment by yuru7** [comment]
ご報告ありがとうございます。再現が取れました。
https://github.com/yuru7/juisee/commit/8b3951ce5d4a8a94c44763d34bc1010a738bc5e0 のコミットで修正してみましたので、最新のビルドスクリプトでビルドしてみていただけますか？

**Comment by gixim** [comment]
早速のご対応ありがとうございます。
HW版、35版ともに `U+3000` にグリフが反映されているのを確認できました。
実際にインストールして使ってみた感じも問題なさそうです。

![Screenshot 2024-08-21 012042](https://github.com/user-attachments/assets/2289768e-e9e7-483f-aac7-44d036d187bf)
![Screenshot 2024-08-21 012625](https://github.com/user-attachments/assets/1a9891d0-b0a6-4ac0-847b-a5d70b62bd18)

**Comment by yuru7** [comment]
確認ありがとうございました。クローズします。
